version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_bento
    environment:
      POSTGRES_USER: bento
      POSTGRES_PASSWORD: bento
      POSTGRES_DB: bento-fees
    ports:
      - "5432:5432"
    volumes:
      - ./docker-config/postgres_data:/var/lib/postgresql/data
      - ./docker-config/init-scripts:/docker-entrypoint-initdb.d

volumes:
  postgres_data: